import os
from dotenv import load_dotenv
from langchain.chat_models import init_chat_model
from langchain.agents import create_agent
from langchain.messages import ToolMessage
from langchain.tools import tool
from langchain_chroma import Chroma
from langchain_ollama import OllamaEmbeddings

load_dotenv()
vector_store = Chroma(embedding_function=OllamaEmbeddings(model="qwen3-embedding"), 
                                   persist_directory="./DocumentationRag/chroma_db")

model = init_chat_model("qwen3:1.7b", temperature=0.0, model_provider="ollama")


@tool(response_format="content_and_artifact")
def search_docs(query: str) -> str:
    """Retrieve relevant documents to help answer the user's question on langchain."""
    results = vector_store.as_retriever().invoke(query, k=5)
    return "\n\n".join(
        [f"Source:{result.metadata.get('source', 'Unknown')} Content:\n{result.page_content}" for  result in results]),results

def run_llm(query: str):
    """Run the RAG pipeline to answer the user's question using retrieved documents.
    Args:
        query (str): The user's question to be answered.
    Returns:
        Dictionary containing:
            - answer: The answer generated by the LLM based on the retrieved documents.
            - context (list): The list of retrieved documents that were used to generate the answer.
    """
    system_prompt=(
        "You are a helpful assistant for answering questions about langchain."
        "You have access to a tool that can retrieve relevant documents to help answer the user's question."
        "Use the tool to retrieve relevant documents before answering the user's question."
        "Always cite the source of the information you use to answer the question."
        "Use the retrieved documents to answer the user's question. If you don't know the answer, say you don't know. "
        "Always use all the retrieved documents to answer the question and provide a comprehensive answer."
    )
    agent = create_agent(model=model, tools=[search_docs], system_prompt=system_prompt)
    message=[{"role":"user","content":query}]
    response = agent.invoke({"messages": message})
    answer= response["messages"][-1].content
    context_docs=[]
    for message in response["messages"]:
        if isinstance(message, ToolMessage) and hasattr(message, "artifact"):
            if isinstance (message.artifact, list): #if the tool returns a list of documents, we want to extend the context_docs list with those documents.
                context_docs.extend(message.artifact)
    return {"answer": answer, "context": context_docs}

if __name__ == "__main__":
    print(run_llm("What is langchain?"))